version: "2" # The Docker version

volumes:
    mongo_volume:

services:
    app:
        image: node:14.7
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        working_dir: /usr/src/app
        depends_on:
            - mongo
        ports:
            - 3000:8080
        command: >
            bash -c "
                npm install &&
                npx nodemon server.js
            "

    mongo:
        image: mongo:4.4
        expose:
            - 27017
        ports:
            - 27017:27017
        volumes:
            - "mongo_volume:/usr/src/data/db"