FROM node:14.7.0

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Dependencies
COPY package.json .
COPY package-lock.json .
RUN npm install

# Source Code
COPY server.js .
COPY app ./app

EXPOSE 8080
CMD node server.js
